### ISSUE TITLE
jobcatcher -s crashes when a job provider website is not (x)html complient?

### ISSUE THREAD

**Issue by yscialom** [yoannsculo/JobCatcher#1]
See attached log:
$ ./jobcatcher.py -s
Fetching CENTREJOB
main date Sat, 12 Oct 2013 00:00:00 +0200
Downloading http://www.centrejob.com/clients/offres_chartees/offre_chartee_modele.aspx?numoffre=77148&de=consultation#xtor=RSS-105217407
Processing 77148
Downloading http://www.centrejob.com/clients/offres_chartees/offre_chartee_modele.aspx?numoffre=77143&de=consultation#xtor=RSS-105217407
Processing 77143
Fetching PROGRESSIVE
Traceback (most recent call last):
  File "./jobcatcher.py", line 220, in <module>
    bot.run()
  File "./jobcatcher.py", line 135, in run
    item.fetch()
  File "/home/yscialom/Etudes/recherche-emploi/JobCatcher/jobboards/Progressive.py", line 103, in fetch
    self.fetch_url(url)
  File "/home/yscialom/Etudes/recherche-emploi/JobCatcher/jobboards/Progressive.py", line 41, in fetch_url
    xmldoc = minidom.parseString( content )
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 1931, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: mismatched tag: line 58, column 6

**Comment by yscialom** [comment]
Here is a temporary patch; i'll eventually fork and pull-request if I write more patches.

<pre>
From 24e1b01c0625d2e1bf2df62a8df577ba390ddf22 Mon Sep 17 00:00:00 2001
From: yscialom <yankel.scialom@mail.com>
Date: Tue, 22 Oct 2013 16:37:32 +0200
Subject: [PATCH] improve resilience to ill-formed html pages
---
 jobcatcher.py | 5 ++++-
 1 file changed, 4 insertions(+), 1 deletion(-)
diff --git a/jobcatcher.py b/jobcatcher.py
index 59741fb..6774db3 100755
--- a/jobcatcher.py
+++ b/jobcatcher.py
@@ -132,7 +132,10 @@ class JobCatcher():
 
     def run(self):
         for item in self.jobBoardList:
-            item.fetch()
+            try:
+                item.fetch()
+             except:
+                print "Ignored (parsing error)."
 
 if __name__ == '__main__':
     parser = OptionParser(usage = 'syntax: %prog [options] <from> [to]')
-- 
1.8.3.2
</pre>

NB: I may have f***ed-up somewhere with the tabs vs. spaces.

**Comment by yoannsculo** [comment]
Oh, thanks Yankel !!
You're right. I'll patch this.

**Comment by yscialom** [comment]
Here is an update fot Apec. Unfortunatly, the rss feed of Progressive have been reworked and did not include the publication date and the job location anymore. I've contacted the webmaster and he put it back :) I'll write a patch tonight (http://www.progressiverecruitment.com/fr/job-search?task=searchAdverts&form-keywords=*&form-job-type=2&form-sector=0&form-country=69&form-jobs-salary=0&form-order-field=&form-order-dir=DESC&redirect=0&format=feed&type=rss).

<pre>From f9613535a3286c965937169e4d73a4f28e82bd0c Mon Sep 17 00:00:00 2001
From: yscialom <yankel.scialom@mail.com>
Date: Wed, 23 Oct 2013 02:17:10 +0200
Subject: [PATCH 1/3] update Apec JobBoard
---
 jobboards/Apec.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
diff --git a/jobboards/Apec.py b/jobboards/Apec.py
index 9365969..eb84746 100755
--- a/jobboards/Apec.py
+++ b/jobboards/Apec.py
@@ -170,7 +170,7 @@ class ApecOffer(Offer):
                 if matchObj:
                     self.company = matchObj.group(1)
 
-            if (th.text == u'Type de contrat :'):
+            if (th.text == u'Type de contrat :' or th.text == u'Nombre de postes :'):
                 self.contract = HTMLParser().unescape(td.text)
                 self.cleanContract()
 
-- 
1.8.3.2
</pre>

**Comment by yscialom** [comment]
Well, I met some trouble to update the Progressive Jobboard. There is no data on the job location, type or salary in the RSS anymore.
