### ISSUE TITLE
Bug in -u function

### ISSUE THREAD

**Issue by yscialom** [yoannsculo/JobCatcher#19]
./jobcatcher.py -u 'http://ec.europa.eu/eures/eures-searchengine/servlet/ShowJvServlet?lg=FR&pesId=62&uniqueJvId=009XWYB&nnImport=false'
Traceback (most recent call last):
  File "./jobcatcher.py", line 647, in <module>
    moduleClass = getattr(module, 'Apec')
AttributeError: 'module' object has no attribute 'Apec'

**Comment by badele** [comment]
The actually function is not oriented object, it is hard-coded with l'Apec. temporary i propose remove this feature.

**Comment by yscialom** [comment]
It would be a good idea to close this ticket.
