### ISSUE TITLE
Dynamic report does not work on google chrome

### ISSUE THREAD

**Issue by yscialom** [yoannsculo/JobCatcher#28]
Google Chrome (tested version 30) does not accept the folowing syntax:

``` javascript
attribute: function(arg = default_value) {
   ...
}
```

It may also refuse any sort of default value for a function argument.

**Comment by yscialom** [comment]
Please confirm bugfix on various browsers.

**Comment by yoannsculo** [comment]
It works fine for me on Ubuntu 12.04 with:
- Google Chrome Version 30.0.1599.114
- Firefox 25.0
