### ISSUE TITLE
[Report] Salary filter bar and salary bounds overlap

### ISSUE THREAD

**Issue by yoannsculo** [yoannsculo/JobCatcher#34]

**Comment by yscialom** [comment]
Screenshot or it did not happen.

**Comment by yoannsculo** [comment]
![capture du 2013-11-22 09 30 17](https://f.cloud.github.com/assets/691328/1599229/6d52f332-5350-11e3-98b6-132dfd2ed834.png)

On both Firefox and Chrome.

**Comment by yscialom** [comment]
I'll take care. How height was your firefox window at the time of the screenshot?

**Comment by yoannsculo** [comment]
1080px. In was in full screen : 1920x1080
