### ISSUE TITLE
[Report] 'NA' Salary filter seems to filter offers without 'NA' strings

### ISSUE THREAD

**Issue by yoannsculo** [yoannsculo/JobCatcher#41]
For example, I can see an offer with the 'SMIC' string when I don't enable NA filtering. If I do, I can't find the SMIC offer anymore. Same thing for other strings such as 'Negociable', 'A determiner', 'selon CCN51', ... that should not disappear untill I put them in the filter :P

**Comment by yscialom** [comment]
What do you mean by "when i don't enable NA filtering?" Do you mean "when i uncheck the NA box" or "when i check it?"

**Comment by yoannsculo** [comment]
Sorry, I wasn't very clear.

I meant that when I check the NA box I see offers. Some of them disappear when I uncheck the box. Part of them are 'NA' offers, that's fine. But others disappear whereas they don't show any 'NA' string in their salary field.

**Comment by yscialom** [comment]
It's due to the fact that are considered NA salary any string whom I can't
extract a precise salary from. "SMIC" is one of them. I agree it can be
improved, shall we plan it for the 1.1.0? Along with this enhancement, we
could add the support for salary expressed in other units that
[k]€/year:monthly, weekly(?), daily(?) and hourly wages.

**Comment by yoannsculo** [comment]
For me, this is not the job of the Javascript dynamic part. The dynamic filter should be there only to filter NA offers.
Other formats should be processed into the Python code.
If the string is unknown we should keep it unchanged. Hence, I don't recommand to filter it with your NA dynamic filter until we handle the string into our python filters.

**Comment by yoannsculo** [comment]
Following to our IRC meeting, we decided not to filter other offers than 'NA'
Other salary format are supposed to be filtered in the Python part.
This salary filtering is a big feature we will put into the v1.1.x
