### ISSUE TITLE
[Report] Increase size of the contract filter drop-down list

### ISSUE THREAD

**Issue by yoannsculo** [yoannsculo/JobCatcher#43]
on Firefox
![capture du 2013-11-22 10 03 28](https://f.cloud.github.com/assets/691328/1599355/0c5f5fc0-5355-11e3-9533-47873a2eb552.png)

on Chrome the bug is worst
![capture du 2013-11-22 10 05 22](https://f.cloud.github.com/assets/691328/1599369/3df75cae-5355-11e3-92db-60ab23b2b228.png)

**Comment by yscialom** [comment]
I'll take care. How wide was your firefox window at the screenshot time?

**Comment by yoannsculo** [comment]
In full screen 1920x1080

**Comment by yscialom** [comment]
bugfix commited on 8a5afe6.
