### ISSUE TITLE
[Report] Move the github link, add index link where github is.

### ISSUE THREAD

**Issue by yscialom** [yoannsculo/JobCatcher#64]

**Comment by yscialom** [comment]
Test page (subject to changes without notice) : http://yankee.sierra77.free.fr/jobcatcher/default/test-issue-64.html.

I've no idea where to put the github logo. Please advise.

**Comment by yscialom** [comment]
TODO: change the logo binary file and replace white pixels by transparent ones.

**Comment by yoannsculo** [comment]
My solution:
- Remove the github logo, we don't need it.
- Just put a github link in the footer. On "JobCatcher" text. later if we create a website, it will link to it.

**Comment by yscialom** [comment]
- Commit 66698d8 moved the github logo into the footer (alos, reduced its size).
- Commit 4ed8575 added a link to ../index.html.
