### ISSUE TITLE
[Report] Job Board popup should stay inside the screen.

### ISSUE THREAD

**Issue by yscialom** [yoannsculo/JobCatcher#65]

**Comment by yoannsculo** [comment]
![capture du 2013-11-27 16 47 40](https://f.cloud.github.com/assets/691328/1632633/45bacb5e-577b-11e3-95fc-1de8b9825beb.png)
I still have the bug here with Firefox.

**Comment by yscialom** [comment]
Did you pull?
![capture du 2013-11-27 16 50 17](https://f.cloud.github.com/assets/1231051/1632672/bb731fae-577b-11e3-974b-bed528d6147c.png)
(Firefox 25)

**Comment by yoannsculo** [comment]
Yes, I'm on 8e46a8a

**Comment by yoannsculo** [comment]
Oh my bad. It works fine. You pushed the fix between my fetch and my comment :P
