### ISSUE TITLE
Store original raw salary information and filtered one in two separate table fields

### ISSUE THREAD

**Issue by yoannsculo** [yoannsculo/JobCatcher#7]

**Comment by yscialom** [comment]
Where are we concerning this issue?.

**Comment by yoannsculo** [comment]
This task has been handled by @badele in his recent refactoring work.
Original data is now stored into jobboard-specific tables. Those data are not supposed to be filtered/changed.
Only the 'offers' table is a result of filtering from those jobboard-specific tables
