### ISSUE TITLE
[Report] Bug on sorting

### ISSUE THREAD

**Issue by yscialom** [yoannsculo/JobCatcher#70]

**Comment by yoannsculo** [comment]
Can you please give us more details ?

**Comment by yscialom** [comment]
It's hard to do so. Here is a procedure to reproduce the bug:
1. Load page
2. Click on the title column head (it'll sort\* the displayed
   offers*according to their title : first bug, it should sort the whole
   table, then
   pick the first offers)
3. Click on the pubdate column head (???)
4. Click again on the pubdate column head (???)

**Comment by yscialom** [comment]
The sorting feature was removed.

**Comment by yoannsculo** [comment]
Should we consider to postpone it for the v1.1.0 ? Or do you think the feature should be officialy removed ?

**Comment by yscialom** [comment]
I think it's useless. Who wants to sort the table by job title rather than
searching a specific pattern?
